name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [pull_request, push]
jobs:
  Run-a-test:
    runs-on: ubuntu-latest
    steps:
      - name: Updating SO
        run: sudo apt-get update
      
      - name: Installing Chrome Driver
        uses: nanasess/setup-chromedriver@v2
      
      - name: Install selenium
        run: pip install selenium
        
      - name: Install webDriverManger
        run: pip install webdriver-manager
     
      - uses: actions/checkout@v3
        
        
      - name: Run test
        run: python3 selenium/teste.py
        if: ${{ failure() }}
