name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  Run-a-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install selenium
        run: pip install selenium
     
      - uses: actions/checkout@v3
        
        
      - name: Run test
        run: python3 selenium/teste.py
